"""Write the knowledge-base measurement docs from the CSVs, so the numbers can't drift from the data.

  python -m scripts.kb_report --category basics      # rewrites mds/kb-token-stats-basics.md
  python -m scripts.kb_report --summary              # rewrites mds/kb-eval-summary.md (all categories with results)

Reads mds/data/<category>_{docs,sections,paragraphs}.csv (scripts.kb_token_stats), eval_<category>_* (scripts.eval_retrieval,
scripts.eval_generation) and tests/data/retrieval_eval_<category>.yaml. Hand-written text between the
<!-- notes:start --> / <!-- notes:end --> and <!-- findings:start --> / <!-- findings:end --> markers is kept.
"""
from __future__ import annotations

import argparse
import csv
import re
import statistics as st
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
MDS = ROOT / "mds"
DATA = MDS / "data"
VARIANTS = ("max512", "max250")
BANDS = (("S", "< 150"), ("M", "150–249"), ("L", "250–512"), ("XL", "> 512"))


def rows(name: str) -> list[dict]:
    path = DATA / name
    return list(csv.DictReader(open(path))) if path.exists() else []


def n(x) -> str:
    return f"{int(x):,}"


def q(v: list[int], parts: int, i: int) -> int:
    return int(st.quantiles(v, n=parts, method="inclusive")[i]) if len(v) > 1 else v[0]


def dist_cells(v: list[int]) -> str:
    return " | ".join(n(x) for x in (min(v), q(v, 4, 0), int(st.median(v)), q(v, 4, 2), q(v, 10, 8), max(v), int(st.mean(v))))


def size_row(v: list[int]) -> str:
    c = [sum(x < 150 for x in v), sum(150 <= x < 250 for x in v), sum(250 <= x < 400 for x in v), sum(400 <= x < 512 for x in v), sum(x >= 512 for x in v)]
    return " | ".join(str(x) for x in c)


def kept(old: str, tag: str, default: str) -> str:
    m = re.search(rf"<!-- {tag}:start -->\n(.*?)<!-- {tag}:end -->", old, re.S)
    return f"<!-- {tag}:start -->\n{m.group(1) if m else default}<!-- {tag}:end -->"


def gen_cell(r: dict) -> str:
    if r["declined"] == "True" and r["in_scope"] == "True":
        return "declined"
    f = "–" if r["faithfulness"] == "" else f"{float(r['faithfulness']):.2f}"
    return f"{r['relevance']} / {f} / {r['correctness']} / {float(r['completeness']):.2f}"


def gen_key(r: dict) -> float:
    if r["declined"] == "True":
        return 0
    return int(r["relevance"]) + int(r["correctness"]) + float(r["completeness"]) * 5 + float(r["faithfulness"] or 1) * 5


def category_doc(cat: str) -> str:
    D, S, P = rows(f"{cat}_docs.csv"), rows(f"{cat}_sections.csv"), rows(f"{cat}_paragraphs.csv")
    if not D:
        raise SystemExit(f"no stats for {cat}: run python -m scripts.kb_token_stats --category {cat} first")
    qfile = ROOT / "tests" / "data" / f"retrieval_eval_{cat}.yaml"
    tested = qfile.exists()                          # a category with only token stats has no questions yet
    qs = yaml.safe_load(open(qfile)) if tested else []
    ans = [x for x in qs if x["expect"]]
    out_path = MDS / f"kb-token-stats-{cat}.md"
    old = out_path.read_text() if out_path.exists() else ""
    L = []
    w = L.append

    w(f"# Knowledge-base token statistics: {cat}\n")
    if tested:
        w(f"Measurements of the `{cat}` source pages, a retrieval test of two chunk limits and an answer-quality test of the same")
        w("limits. The design these numbers feed into is [rag-data-design.md](rag-data-design.md); all categories side by side:")
    else:
        w(f"Measurements of the `{cat}` source pages and how the chunker cuts them at two chunk limits. **Token statistics only: no")
        w("retrieval or answer-quality test yet.** The design these numbers feed into is [rag-data-design.md](rag-data-design.md); all categories side by side:")
    w("[kb-eval-summary.md](kb-eval-summary.md). Generated by `python -m scripts.kb_report --category " + cat + "` from the")
    w("CSVs in [data/](data/); only the notes and findings are written by hand.\n")
    w(kept(old, "notes", "") + "\n")
    w(f"- **Sample:** the {len(D)} `{cat}` pages in [kb_topics.yaml](../src/data/kb_topics.yaml), full Wikipedia text (not")
    w(f"  truncated), saved in [tests/data/kb_snapshot/{cat}/](../tests/data/kb_snapshot/{cat}/).")
    w("- **Tokenizer:** `BAAI/bge-small-en-v1.5`, the embedding model, without `[CLS]`/`[SEP]`.")
    w("- **Raw vs clean:** \"raw\" is the text as `WikiClient.get_page()` returns it. \"Clean\" has each MathML formula dump collapsed")
    w("  to inline LaTeX; all section and paragraph figures use clean text.")
    w("- **Section** = text under one heading (`##`–`#####`), excluding its subsections. **Paragraph** = one line of the source")
    w("  text; list items count as separate paragraphs.\n")
    w(f"Data: [{cat}_docs.csv](data/{cat}_docs.csv), [{cat}_sections.csv](data/{cat}_sections.csv), "
      f"[{cat}_paragraphs.csv](data/{cat}_paragraphs.csv).\n")
    w("## Reproduce\n\n```bash")
    w(f"python -m scripts.kb_token_stats --category {cat} --pages-dir tests/data/kb_snapshot/{cat}")
    if tested:
        w(f"python -m scripts.eval_retrieval --category {cat}      # builds the max512 / max250 test collections")
        w(f"python -m scripts.eval_generation --category {cat}     # needs OPENAI_API_KEY")
    else:
        w(f"python -m scripts.eval_retrieval --category {cat} --chunks-only    # chunk lists for max 512 and max 250")
    w(f"python -m scripts.kb_report --category {cat}\n```\n")

    w("## Documents\n")
    w("| Document | Sections | Paragraphs | Words | Tokens raw | Tokens clean | Tokens / word | Sections with maths |")
    w("|---|---|---|---|---|---|---|---|")
    for d in sorted(D, key=lambda d: d["doc"]):
        w(f"| {d['doc']} | {d['sections']} | {d['paragraphs']} | {n(d['words'])} | {n(d['tokens_raw'])} | {n(d['tokens_clean'])} | "
          f"{float(d['tokens_per_word']):.2f} | {d['math_sections']} |")
    tot = {k: sum(int(d[k]) for d in D) for k in ("sections", "paragraphs", "words", "tokens_raw", "tokens_clean", "math_sections")}
    w(f"| **Total** | **{tot['sections']}** | **{tot['paragraphs']}** | **{n(tot['words'])}** | **{n(tot['tokens_raw'])}** | "
      f"**{n(tot['tokens_clean'])}** | | **{tot['math_sections']}** |\n")

    for title, R in (("Sections", S), ("Paragraphs", P)):
        w(f"## {title} (tokens)\n")
        w("| Document | Min | p25 | Median | p75 | p90 | Max | Mean |\n|---|---|---|---|---|---|---|---|")
        for d in sorted(D, key=lambda d: d["doc"]):
            w(f"| {d['doc']} | {dist_cells([int(r['tokens']) for r in R if r['doc'] == d['doc']])} |")
        v = [int(r["tokens"]) for r in R]
        w(f"| **All {len(v)} {title.lower()}** | {' | '.join(f'**{c.strip()}**' for c in dist_cells(v).split('|'))} |\n")
        w(f"| Size | < 150 | 150–249 | 250–399 | 400–511 | ≥ 512 |\n|---|---|---|---|---|---|\n| {title} | {size_row(v)} |\n")
        if title == "Sections":
            w("Largest sections:\n\n| Tokens | Document › section | Paragraphs |\n|---|---|---|")
            for r in sorted(S, key=lambda r: -int(r["tokens"]))[:6]:
                w(f"| {n(r['tokens'])} | {r['doc']} › {r['section'].replace(' > ', ' › ')} | {r['paragraphs']} |")
            w("")

    w("## Tokens per word\n")
    w("| Text | Sections | Words | bge tokens | Tokens / word |\n|---|---|---|---|---|")
    for label, g in (("Sections without formulas", [r for r in S if r["has_math"] != "True"]),
                     ("Sections with formulas", [r for r in S if r["has_math"] == "True"])):
        if g:
            ww, tt = sum(int(r["words"]) for r in g), sum(int(r["tokens"]) for r in g)
            w(f"| {label} | {len(g)} | {n(ww)} | {n(tt)} | {tt / ww:.2f} |")
    w("")

    chunks = {v: rows(f"eval_{cat}_chunks_{v}.csv") for v in VARIANTS}
    if all(chunks.values()):
        w("## Chunks produced\n")
        w("Actual chunker output for the two limits compared" + (" below" if tested else "") + " (one chunk per section, never merged):\n")
        w("| Limit | Chunks | Median | Min | Max | < 50 | 50–149 | 150–249 | 250–399 | 400–512 | Sections split |")
        w("|---|---|---|---|---|---|---|---|---|---|---|")
        for v, cs in chunks.items():
            t = [int(c["tokens"]) for c in cs]
            split = len({(c["doc_id"], c["section"]) for c in cs if c["pieces"] != "1"})
            w(f"| {v.replace('max', 'max ')} | {len(t)} | {int(st.median(t))} | {min(t)} | {max(t)} | {sum(x < 50 for x in t)} | "
              f"{sum(50 <= x < 150 for x in t)} | {sum(150 <= x < 250 for x in t)} | {sum(250 <= x < 400 for x in t)} | "
              f"{sum(400 <= x <= 512 for x in t)} | {split} |")
        w(f"\nChunk lists: [max 512](data/eval_{cat}_chunks_max512.csv), [max 250](data/eval_{cat}_chunks_max250.csv).\n")

    summ = {r["variant"]: r for r in rows(f"eval_{cat}_summary.csv")}
    res = {(r["variant"], r["id"]): r for r in rows(f"eval_{cat}_results.csv")}
    if summ:
        bands = {b: sum(x["band"] == b for x in ans) for b, _ in BANDS}
        w("## Retrieval test: max 512 vs max 250\n")
        w(f"`python -m scripts.eval_retrieval --category {cat}`: the chunker with each limit, `bge-small-en-v1.5` via `fastembed`,")
        w(f"local Qdrant, top 5, search restricted to the `{cat}` category.\n")
        w(f"- **Questions:** {len(qs)} in [retrieval_eval_{cat}.yaml](../tests/data/retrieval_eval_{cat}.yaml): {len(ans)} answerable "
          f"({', '.join(f'{c} {b}' for b, c in bands.items())}) and {len(qs) - len(ans)} out of scope.")
        w("- **hit@k:** a chunk from one of the question's correct sections is in the top k. **hint@5:** the answer phrase")
        w("  itself is in a retrieved chunk (plain text match). **MRR:** mean of 1/rank of the correct section (0 if missed).")
        w(f"- **Raw results:** [eval_{cat}_results.csv](data/eval_{cat}_results.csv), [eval_{cat}_summary.csv](data/eval_{cat}_summary.csv).\n")
        a, b = summ["max512"], summ["max250"]
        w(f"### Summary ({a['questions']} answerable questions)\n\n| | max 512 | max 250 |\n|---|---|---|")
        w(f"| Chunks | {a['chunks']} | {b['chunks']} |\n| Sections split | {a['sections_split']} | {b['sections_split']} |")
        nq = int(a["questions"])
        for k, label in (("hit@1", "hit@1"), ("hit@3", "hit@3"), ("hit@5", "hit@5"), ("mrr", "MRR"), ("hint@5", "hint@5 (answer text retrieved)")):
            x, y = float(a[k]), float(b[k])
            fx = f"{x:.3f}" if k == "mrr" else f"{int(x)} ({100 * x / nq:.0f}%)" if k in ("hit@1", "hit@5") else str(int(x))
            fy = f"{y:.3f}" if k == "mrr" else f"{int(y)} ({100 * y / nq:.0f}%)" if k in ("hit@1", "hit@5") else str(int(y))
            if x > y:
                fx = f"**{fx}**"
            elif y > x:
                fy = f"**{fy}**"
            w(f"| {label} | {fx} | {fy} |")
        w(f"| Mean tokens sent to the LLM (top 5) | {n(a['mean_context_tokens'])} | {n(b['mean_context_tokens'])} |\n")
        w("### By size of the expected section (hit@1 / hit@5 / hint@5 / MRR)\n\n| Band | n | max 512 | max 250 |\n|---|---|---|---|")
        for band, label in BANDS:
            g = [x for x in ans if x["band"] == band]
            if not g:
                continue
            cells = []
            for v in VARIANTS:
                rs = [res[(v, x["id"])] for x in g]
                ranks = [int(r["rank"]) if r["rank"] else None for r in rs]
                cells.append(f"{sum(k == 1 for k in ranks)} / {sum(bool(k) for k in ranks)} / {sum(bool(r['hint_rank']) for r in rs)} / "
                             f"{sum(1 / k for k in ranks if k) / len(rs):.2f}")
            w(f"| {band} ({label}) | {len(g)} | {cells[0]} | {cells[1]} |")
        w("\n### Per question\n")
        w("Each cell: **section rank / phrase rank** in the top 5 (1 is best; – = not in the top 5). Bold marks the better limit.\n")
        w("| id | Band | Question | Answer phrase | max 512 | max 250 |\n|---|---|---|---|---|---|")
        key = lambda r: (int(r["rank"]) if r["rank"] else 9, int(r["hint_rank"]) if r["hint_rank"] else 9)
        for x in ans:
            ra, rb = res[("max512", x["id"])], res[("max250", x["id"])]
            ca, cb = f"{ra['rank'] or '–'} / {ra['hint_rank'] or '–'}", f"{rb['rank'] or '–'} / {rb['hint_rank'] or '–'}"
            if key(ra) < key(rb):
                ca = f"**{ca}**"
            elif key(rb) < key(ra):
                cb = f"**{cb}**"
            w(f"| {x['id']} | {x['band']} | {x['q']} | {' or '.join(f'“{h}”' for h in x['hints'])} | {ca} | {cb} |")
        w("\n### Score threshold\n\n| | max 512 | max 250 |\n|---|---|---|")
        w(f"| Lowest top-1 score, answerable questions | {float(a['min_top1_answerable']):.3f} | {float(b['min_top1_answerable']):.3f} |")
        w(f"| Highest top-1 score, out-of-scope questions | {float(a['max_top1_no_answer']):.3f} | {float(b['max_top1_no_answer']):.3f} |\n")

    G = rows(f"eval_{cat}_generation.csv")
    gs = {r["variant"]: r for r in rows(f"eval_{cat}_generation_summary.csv")}
    if G and gs:
        gb = {(r["variant"], r["id"]): r for r in G}
        w("## Generation test: answer quality\n")
        w(f"`python -m scripts.eval_generation --category {cat}`: for each question and limit, the top-5 chunks go to `gpt-4o-mini`")
        w("(the app's model, temperature 0) with the instruction to answer only from them (≤ 150 words) or say they don't cover")
        w("the question. `gpt-4o-mini` then judges the answer against the chunks and the question's `reference` / `key_points`.")
        w("Because the same model writes and judges, scores may be lenient.\n")
        w("| Metric | Scale | Meaning |\n|---|---|---|")
        w("| Relevance | 1–5 | Does the answer address the question asked? |")
        w("| Faithfulness | 0–1 | Share of the answer's claims supported by the retrieved chunks (hallucination check); not scored for refusals |")
        w("| Correctness | 1–5 | Do the answer's facts agree with the reference answer? |")
        w("| Completeness | 0–1 | Share of the reference key points covered; 0 for a refused answerable question |\n")
        w("Refusals (\"the sources don't cover this\") are detected from the answer text. Raw results, with every answer, unsupported")
        w(f"claim and judge reason: [eval_{cat}_generation.csv](data/eval_{cat}_generation.csv), "
          f"[eval_{cat}_generation_summary.csv](data/eval_{cat}_generation_summary.csv).\n")
        a, b = gs["max512"], gs["max250"]
        w(f"### Summary ({a['questions']} answerable questions)\n\n| | max 512 | max 250 |\n|---|---|---|")
        for k, label, fmt in (("relevance", "Relevance (1–5)", "{:.2f}"), ("faithfulness", "Faithfulness (claims supported)", "{:.2f}"),
                              ("correctness", "Correctness (1–5)", "{:.2f}"), ("completeness", "Completeness (key points covered)", "{:.2f}")):
            x, y = float(a[k]), float(b[k])
            fx, fy = fmt.format(x), fmt.format(y)
            if fx > fy:
                fx = f"**{fx}**"
            elif fy > fx:
                fy = f"**{fy}**"
            w(f"| **{label}** | {fx} | {fy} |")
        w(f"| Fully faithful answers | {a['fully_faithful']} | {b['fully_faithful']} |")
        w(f"| Answerable questions wrongly refused | {a['wrongly_declined']} | {b['wrongly_declined']} |")
        w(f"| Out-of-scope questions refused (should be {a['out_of_scope']}) | {a['out_of_scope_declined']} | {b['out_of_scope_declined']} |\n")
        w("### By size of the expected section (relevance / faithfulness / correctness / completeness)\n")
        w("| Band | n | max 512 | max 250 |\n|---|---|---|---|")
        for band, label in BANDS:
            g = [x for x in ans if x["band"] == band]
            if not g:
                continue
            cells = []
            for v in VARIANTS:
                rs = [gb[(v, x["id"])] for x in g]
                fa = [float(r["faithfulness"]) for r in rs if r["faithfulness"] != ""]
                cells.append(f"{st.mean(int(r['relevance']) for r in rs):.2f} / {(st.mean(fa) if fa else 0):.2f} / "
                             f"{st.mean(int(r['correctness']) for r in rs):.2f} / {st.mean(float(r['completeness']) for r in rs):.2f}")
            w(f"| {band} ({label}) | {len(g)} | {cells[0]} | {cells[1]} |")
        w("\n### Per question\n")
        w("Each cell: **relevance / faithfulness / correctness / completeness**. Bold marks the better limit.\n")
        w("| id | Band | Question | max 512 | max 250 |\n|---|---|---|---|---|")
        for x in ans:
            ra, rb = gb[("max512", x["id"])], gb[("max250", x["id"])]
            ca, cb = gen_cell(ra), gen_cell(rb)
            if gen_key(ra) > gen_key(rb):
                ca = f"**{ca}**"
            elif gen_key(rb) > gen_key(ra):
                cb = f"**{cb}**"
            w(f"| {x['id']} | {x['band']} | {x['q']} | {ca} | {cb} |")
        w("")

    w("## Findings\n")
    w(kept(old, "findings", "_To be written._\n"))
    return "\n".join(L) + "\n"


def summary_doc() -> str:
    cats = sorted(p.name[len("eval_"):-len("_summary.csv")] for p in DATA.glob("eval_*_summary.csv") if "generation" not in p.name)
    L = []
    w = L.append
    w("# Knowledge-base evaluation summary\n")
    w("All tested categories side by side, and combined. Generated by `python -m scripts.kb_report --summary`; the per-category")
    w("details are in `kb-token-stats-<category>.md`.\n")
    w("## Retrieval\n\n| Category | Answerable | Limit | hit@1 | hit@5 | hint@5 | MRR | Tokens to LLM |\n|---|---|---|---|---|---|---|---|")
    tot = {v: {"q": 0, "h1": 0, "h5": 0, "hint": 0, "rr": 0.0, "ctx": 0.0} for v in VARIANTS}
    for c in cats:
        for r in rows(f"eval_{c}_summary.csv"):
            v, nq = r["variant"], int(r["questions"])
            w(f"| [{c}](kb-token-stats-{c}.md) | {nq} | {v.replace('max', 'max ')} | {r['hit@1']} | {r['hit@5']} | {r['hint@5']} | {float(r['mrr']):.3f} | {n(r['mean_context_tokens'])} |")
            t = tot[v]
            t["q"] += nq
            t["h1"] += int(r["hit@1"])
            t["h5"] += int(r["hit@5"])
            t["hint"] += int(r["hint@5"])
            t["rr"] += float(r["mrr"]) * nq
            t["ctx"] += float(r["mean_context_tokens"]) * nq
    for v, t in tot.items():
        if t["q"]:
            w(f"| **All** | **{t['q']}** | **{v.replace('max', 'max ')}** | **{t['h1']}** | **{t['h5']}** | **{t['hint']}** | "
              f"**{t['rr'] / t['q']:.3f}** | **{n(t['ctx'] / t['q'])}** |")
    w("\nMRR and tokens for **All** are weighted by the number of questions.\n")
    w("## Answer quality\n\n| Category | Limit | Relevance | Faithfulness | Correctness | Completeness | Wrongly refused | Out-of-scope refused |")
    w("|---|---|---|---|---|---|---|---|")
    gt = {v: [] for v in VARIANTS}
    oos = {v: [0, 0] for v in VARIANTS}
    for c in cats:
        G = rows(f"eval_{c}_generation.csv")
        for r in rows(f"eval_{c}_generation_summary.csv"):
            v = r["variant"]
            w(f"| [{c}](kb-token-stats-{c}.md) | {v.replace('max', 'max ')} | {float(r['relevance']):.2f} | {float(r['faithfulness']):.2f} | "
              f"{float(r['correctness']):.2f} | {float(r['completeness']):.2f} | {r['wrongly_declined']} | {r['out_of_scope_declined']} of {r['out_of_scope']} |")
            gt[v] += [x for x in G if x["variant"] == v and x["in_scope"] == "True"]
            oos[v][0] += int(r["out_of_scope_declined"])
            oos[v][1] += int(r["out_of_scope"])
    for v, rs in gt.items():
        if rs:
            fa = [float(x["faithfulness"]) for x in rs if x["faithfulness"] != ""]
            w(f"| **All ({len(rs)})** | **{v.replace('max', 'max ')}** | **{st.mean(int(x['relevance']) for x in rs):.2f}** | **{st.mean(fa):.2f}** | "
              f"**{st.mean(int(x['correctness']) for x in rs):.2f}** | **{st.mean(float(x['completeness']) for x in rs):.2f}** | "
              f"**{sum(x['declined'] == 'True' for x in rs)}** | **{oos[v][0]} of {oos[v][1]}** |")
    w("\n**All** averages every answerable question across categories (faithfulness over answered questions only).")
    return "\n".join(L) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--category")
    ap.add_argument("--summary", action="store_true")
    args = ap.parse_args()
    if args.category:
        (MDS / f"kb-token-stats-{args.category}.md").write_text(category_doc(args.category))
        print(f"wrote mds/kb-token-stats-{args.category}.md")
    if args.summary:
        (MDS / "kb-eval-summary.md").write_text(summary_doc())
        print("wrote mds/kb-eval-summary.md")


if __name__ == "__main__":
    main()
